
trading_mode: demo

exchange:
  name: binance
  symbols:
    - BTC/USDT
    - ETH/USDT
  timeframes:
    - 1m
    - 5m
    - 15m
    - 1h
    - 4h
  
  demo_api:
    base_url: https://testnet.binance.vision
  
  live_api:
    base_url: https://api.binance.com

data:
  websocket:
    reconnect_delay: 5  # seconds
    max_reconnect_attempts: 10
    ping_interval: 30  # seconds
  
  historical:
    lookback_days: 30
    candle_limit: 1000
  
  buffer:
    max_size: 1000  # maximum candles to keep in memory

database:
  sqlite:
    path: ./data/trading_bot.db
  
  redis:
    db: 0
    decode_responses: true

logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: json  # json or text
  rotation: 10 MB
  retention: 30 days
  
  files:
    main: ./logs/trading_bot.log
    trades: ./logs/trades.log
    errors: ./logs/errors.log
    data: ./logs/data.log

indicators:
  sma:
    periods: [20, 50, 200]
  ema:
    periods: [12, 26, 50, 200]
  rsi:
    period: 14
  macd:
    fast: 12
    slow: 26
    signal: 9
  bollinger_bands:
    period: 20
    std_dev: 2
  atr:
    period: 14
  stochastic:
    k_period: 14
    d_period: 3
  cci:
    period: 20
