
strategies:
  simple_rsi:
    enabled: false
    timeframe: 5m
    parameters:
      rsi_period: 14
      oversold_threshold: 30
      overbought_threshold: 70
      confidence: 0.6
  
  scalping:
    enabled: false
    timeframe: 1m
    parameters:
      profit_target_pct: 0.3
      stop_loss_pct: 0.2
      volume_threshold: 1.5  # multiplier of average volume
      max_trades_per_day: 50
      max_leverage: 5
  
  momentum:
    enabled: false
    timeframe: 1h
    parameters:
      ema_fast: 12
      ema_slow: 26
      adx_threshold: 25
      rsi_threshold: 50
      profit_target_pct: 5.0
      stop_loss_pct: 2.0
      max_leverage: 5
  
  mean_reversion:
    enabled: false
    timeframe: 15m
    parameters:
      bb_period: 20
      bb_std_dev: 2
      rsi_oversold: 30
      rsi_overbought: 70
      profit_target_pct: 2.0
      stop_loss_pct: 1.0
      max_leverage: 3
